import { Injectable, Logger } from '@nestjs/common'
import PDFDocument from 'pdfkit'

export interface ContractPdfData {
  contractRef: string
  propertyAddress: string
  city: string
  stateCode: string
  buyerName: string
  wholesalerName: string
  assignmentPrice: number
  emdAmount: number
  inspectionDays: number
  signedAt: string
  dealId: string
}

export interface EmdPdfData {
  dealRef: string
  propertyAddress: string
  city: string
  stateCode: string
  buyerName: string
  emdAmount: number
  bankName: string
  accountNumber: string
  routingNumber: string
  dueDate: string
}

function formatCurrency(n: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
  }).format(n)
}

@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name)

  generateContractPdf(data: ContractPdfData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 })
        const chunks: Buffer[] = []

        doc.on('data', (chunk) => chunks.push(chunk))
        doc.on('end', () => resolve(Buffer.concat(chunks)))
        doc.on('error', reject)

        doc.fontSize(20).font('Helvetica-Bold').text('TRACT', { align: 'center' })

        doc.fontSize(14).font('Helvetica-Bold').text('Assignment Contract', { align: 'center' })

        doc
          .fontSize(10)
          .font('Helvetica')
          .text(`Contract Ref: ${data.contractRef}`, { align: 'center' })

        doc.moveDown(2)
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke()
        doc.moveDown()

        doc.fontSize(12).font('Helvetica-Bold').text('Property Details')
        doc.moveDown(0.5)
        doc.fontSize(10).font('Helvetica')
        doc.text(`Address: ${data.propertyAddress}`)
        doc.text(`City: ${data.city}`)
        doc.text(`State: ${data.stateCode}`)
        doc.moveDown()

        doc.fontSize(12).font('Helvetica-Bold').text('Parties')
        doc.moveDown(0.5)
        doc.fontSize(10).font('Helvetica')
        doc.text(`Buyer: ${data.buyerName}`)
        doc.text(`Wholesaler: ${data.wholesalerName}`)
        doc.moveDown()

        doc.fontSize(12).font('Helvetica-Bold').text('Deal Terms')
        doc.moveDown(0.5)
        doc.fontSize(10).font('Helvetica')
        doc.text(`Assignment Price: ${formatCurrency(data.assignmentPrice)}`)
        doc.text(`EMD Amount: ${formatCurrency(data.emdAmount)}`)
        doc.text(`Inspection Period: ${data.inspectionDays} days`)
        doc.moveDown()

        doc.fontSize(12).font('Helvetica-Bold').text('Signature')
        doc.moveDown(0.5)
        doc.fontSize(10).font('Helvetica')
        doc.text(`Signed at: ${new Date(data.signedAt).toLocaleString('en-US')}`)
        doc.text('This document was electronically signed via TRACT Private Marketplace.')
        doc.moveDown(2)

        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke()
        doc.moveDown(0.5)
        doc
          .fontSize(8)
          .font('Helvetica')
          .fillColor('gray')
          .text(`Generated by TRACT on ${new Date().toLocaleDateString('en-US')}`, { align: 'center' })

        doc.end()
      } catch (err) {
        this.logger.error('generateContractPdf failed:', err)
        reject(err)
      }
    })
  }

  generateEmdPdf(data: EmdPdfData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 })
        const chunks: Buffer[] = []

        doc.on('data', (chunk) => chunks.push(chunk))
        doc.on('end', () => resolve(Buffer.concat(chunks)))
        doc.on('error', reject)

        doc.fontSize(20).font('Helvetica-Bold').text('TRACT', { align: 'center' })

        doc.fontSize(14).font('Helvetica-Bold').text('EMD Wire Instructions', { align: 'center' })

        doc.fontSize(10).font('Helvetica').text(`Deal Ref: ${data.dealRef}`, { align: 'center' })

        doc.moveDown(2)
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke()
        doc.moveDown()

        doc.fontSize(12).font('Helvetica-Bold').text('Property')
        doc.moveDown(0.5)
        doc.fontSize(10).font('Helvetica')
        doc.text(`Address: ${data.propertyAddress}`)
        doc.text(`Location: ${data.city}, ${data.stateCode}`)
        doc.moveDown()

        doc.fontSize(12).font('Helvetica-Bold').text('Buyer')
        doc.moveDown(0.5)
        doc.fontSize(10).font('Helvetica')
        doc.text(`Name: ${data.buyerName}`)
        doc.moveDown()

        doc.fontSize(12).font('Helvetica-Bold').text('Wire Instructions')
        doc.moveDown(0.5)
        doc.fontSize(10).font('Helvetica')
        doc.text(`Amount: ${formatCurrency(data.emdAmount)}`)
        doc.text(`Bank: ${data.bankName}`)
        doc.text(`Account Number: ${data.accountNumber}`)
        doc.text(`Routing Number: ${data.routingNumber}`)
        doc.text(`Due Date: ${data.dueDate}`)
        doc.moveDown()

        doc.fontSize(12).font('Helvetica-Bold').text('Important')
        doc.moveDown(0.5)
        doc.fontSize(10).font('Helvetica').fillColor('red')
        doc.text(
          'Wire the exact amount shown above. Do not modify any banking details. Contact your title company to verify instructions before wiring.',
        )

        doc.moveDown(2)
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke()
        doc.moveDown(0.5)
        doc
          .fontSize(8)
          .font('Helvetica')
          .fillColor('gray')
          .text(`Generated by TRACT on ${new Date().toLocaleDateString('en-US')}`, { align: 'center' })

        doc.end()
      } catch (err) {
        this.logger.error('generateEmdPdf failed:', err)
        reject(err)
      }
    })
  }
}
