import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

export interface PropertySummaryDetails {
  dealId?: string
  address?: string
  titleHandling?: string
  dealType?: string
  marketStatus?: string
  /** Private amounts are removed upstream, so absent keys are simply not printed. */
  prices?: Record<string, unknown>
}

const PRICE_LABELS: Record<string, string> = {
  agreedAssignmentPrice: 'Agreed property price',
  askingAssignmentPrice: 'Asking price',
  arv: 'After-repair value (ARV)',
  purchasePrice: 'Acquisition price',
  emdAmount: 'Earnest money deposit',
}

const TITLE_HANDLING_LABELS: Record<string, string> = {
  own_rep: 'Buyer uses their own title representative',
  tract: 'Handled by the platform title team',
  buyer: 'Buyer uses their own title representative',
  admin: 'Handled by the platform title team',
  platform: 'Handled by the platform title team',
}

function money(value: unknown): string | null {
  const amount = typeof value === 'string' ? Number(value) : value
  if (typeof amount !== 'number' || !Number.isFinite(amount) || amount <= 0) return null
  return `$${Math.round(amount).toLocaleString('en-US')}`
}

function titleCase(value: string): string {
  return value.replace(/[_-]+/g, ' ').replace(/\b\w/g, character => character.toUpperCase())
}

/**
 * Human-readable replacement for the raw JSON summary that used to ship in the
 * title package. Only the fields present in `details` are printed, so a buyer
 * package silently omits the private amounts stripped upstream.
 */
export async function generatePropertySummaryPdf(
  details: PropertySummaryDetails,
  files: string[],
): Promise<Buffer> {
  const pdf = await PDFDocument.create()
  const page = pdf.addPage([612, 792])
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)
  const regular = await pdf.embedFont(StandardFonts.Helvetica)
  const ink = rgb(0.1, 0.1, 0.12)
  const muted = rgb(0.42, 0.42, 0.48)
  const rule = rgb(0.8, 0.8, 0.84)

  const left = 56
  let y = 736

  const heading = (text: string) => {
    y -= 26
    page.drawText(text.toUpperCase(), { x: left, y, size: 9.5, font: bold, color: muted })
    y -= 8
    page.drawLine({ start: { x: left, y }, end: { x: 556, y }, thickness: 0.7, color: rule })
    y -= 6
  }
  const row = (label: string, value: string) => {
    y -= 18
    page.drawText(label, { x: left, y, size: 9.5, font: regular, color: muted })
    page.drawText(value.slice(0, 60), { x: left + 190, y, size: 10.5, font: bold, color: ink })
  }

  page.drawText('PROPERTY SUMMARY', { x: left, y, size: 20, font: bold, color: ink })
  y -= 18
  page.drawText(
    `Prepared ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    { x: left, y, size: 9.5, font: regular, color: muted },
  )

  heading('Property')
  row('Address', details.address || 'Not provided')
  if (details.dealType) row('Deal type', titleCase(String(details.dealType)))
  if (details.marketStatus) row('Market status', titleCase(String(details.marketStatus)))
  if (details.dealId) row('Deal reference', String(details.dealId))

  const priceRows = Object.entries(details.prices ?? {})
    .map(([key, value]) => [PRICE_LABELS[key] ?? titleCase(key), money(value)] as const)
    .filter((entry): entry is readonly [string, string] => entry[1] !== null)
  if (priceRows.length) {
    heading('Pricing')
    for (const [label, value] of priceRows) row(label, value)
  }

  heading('Title handling')
  const handling = details.titleHandling ? String(details.titleHandling) : ''
  row('Arrangement', TITLE_HANDLING_LABELS[handling] ?? (handling ? titleCase(handling) : 'Not selected'))

  heading('Included in this package')
  for (const file of files) {
    y -= 16
    page.drawText(`•  ${file}`, { x: left, y, size: 10, font: regular, color: ink })
    if (y < 70) break
  }

  page.drawText(
    'Generated by TRACT. Figures reflect the agreement between the parties on the date shown.',
    { x: left, y: 46, size: 8, font: regular, color: muted },
  )

  return Buffer.from(await pdf.save())
}
